### PR TITLE
Fix incorrect register classes causing dependency errors; add new MemH test for dependency checks; remove obsolete MemH tests

### PR DESCRIPTION
**Pull request by leekillough**
This adds a new test `ex7` which detects https://github.com/tactcomplabs/rev/issues/228 on MemH but shows it passing on RevMem.

This also removes the obsolete `memh_1` and `memh_2` test directories, since they aren't used anymore.

### CODE REVIEW

**Review by donofrio — APPROVED** [review]
Looks good to me - new tests are welcome :)

**Comment by leekillough** [comment]
@jleidel  I can merge this, but until I figure out the cause of #228 it will cause one new failure in the tests, instead of passing 100% of tests.

**Comment by jleidel** [comment]
> @jleidel I can merge this, but until I figure out the cause of #228 it will cause one new failure in the tests, instead of passing 100% of tests.

which test?

**Comment by leekillough** [comment]
> > @jleidel I can merge this, but until I figure out the cause of #228 it will cause one new failure in the tests, instead of passing 100% of tests.
> 
> which test?

`ex7` on MemH. `ex7` passes on RevMem. This PR tests both RevMem and MemH on an integer store/load dependency.  This exactly illustrates #228 and the recently duplicated #148 .

**Review by rkabrick — APPROVED** [review]
LGTM... Up to @jleidel to decide if we merge before ex7 passes or not

**Comment by leekillough** [comment]
Fixes https://github.com/tactcomplabs/rev/issues/228. The tables were incorrectly setting `RevRegClass` for a lot of instructions.

Need to go through them all thoroughly and write more tests, but for now, this is a fix.

@jleidel: merge when you're okay. It's passed all CI tests, but I haven't tried the latest SST.

**Comment by leekillough** [comment]
The following register class and instruction format bugs have been fixed:
* `lr.d`'s `rs1Class` and `sc.d`'s `rs2Class` were set to `RegUNKNOWN` instead of `RegGPR`
*  `fmv.x.w`, `fmv.x.d`, `fcvt.w.s`, `fcvt.wu.s`, `fcvt.w.d`, `fcvt.wu.d`, `fcvt.l.d`, `fcvt.lu.d`, `feq.s`, `feq.d`, `flt.s`, `flt.d`, `fle.s`, `fle.d`, `fclass.s`, `fclass.d` had a `rdClass` of `RegFLOAT` instead of `RegGPR`
* `fmv.d.x`, `fcvt.d.w`, `fcvt.d.wu`, `fcvt.d.l` and `fcvt.d.lu` had a `rs1Class` of `RegFLOAT` instead of `RegGPR`
* `srliw` and `sraiw` had a format of `RVTypeR` instead of `RVTypeI` 

I am working on another post-release PR to condense and organize the tables better so that this is less likely to occur.

**Pull request merged**
