### PR TITLE
Unify tests update

### PR DESCRIPTION
**Pull request by vcave**

### CODE REVIEW

**Comment by jleidel** [comment]
induces failures in the following tests: 

```
	  8 - TEST_BGE_BLE (Failed)
	 10 - TEST_MINFFT (Failed)
	 46 - TEST_MUNMAP (Failed)
	 47 - TEST_VECTOR (Failed)
```

**Comment by jleidel** [comment]
rebasing on the latest devel post `pthreads` merge and retesting...

**Comment by leekillough** [comment]
With the latest, I get:
```
          8 - TEST_BGE_BLE (Failed)
         10 - TEST_MINFFT (Failed)
         43 - TEST_FORK (Failed)
         47 - TEST_VECTOR (Failed)
```

`MINFFT` is disabled in `devel` because it's buggy. I will merge the changes to disable it.

**Comment by rkabrick** [comment]
I extended the idea in this PR and made this one. Would be interested in your input @vcave 
 https://github.com/tactcomplabs/rev/pull/211

**Comment by rkabrick** [comment]
#211 has been merged... closing this PR

**Pull request closed without merging**
